### PR TITLE
Release 0.1.0

### PR DESCRIPTION
**Pull request by seamustuohy**
Merging Dev branch for Release 0.1.0

The major change here is that I updated RTFDE to only work with bytes and leave all encoding up to the downstream library. Please update your code as necessary! 

* Updated to only work with bytes.
* Added far greater unicode support.
* Fixed various whitespace issues.
* Added proper htmlrtf support.
* Added support for extracting (but not parsing binary data). 
* Update grammar to be far more explicit when extracting objects.
* Fixes to ensure deencapsulation handles whitespace properly.
* Adds grammar composer to make grammar modifications more clearly defined.
* Adding support for surrogates which use raw unicode instead of 16bit signed encoding.
* Added better handling of parsing unicode HH replacement chars.

### CODE REVIEW

**Comment by seamustuohy** [comment]
Addressed in the 0.1.0 version which is in the final notification and testing stage on [dev](https://github.com/seamustuohy/RTFDE/commit/1b29704a47e6c3a118ebb3ed2ac96e640312f8fb)

Notifying those who look like they are using this library to ensure that they are ready to make necessary updates. (Sorry to those being notified more than once.) I'll be waiting a couple of weeks before I do the full release so folks have a chance test and update their libraries as necessary and/or pin their requirements to the current version of the library. 

*Please report any critical breaking issues (besides the switch to work entirely on binary strings) so I can try to address as many as possible before the release.*

- @Rafiot (MISP - PyMISP - emailobject)
- @twbryan (convert-outlook-msg-file)
- @ShacharKidor, & @moishce (parse-emails)
- @TheElementalOfDestruction (msg-extractor)

**Comment by TheElementalOfDestruction** [comment]
I'm not seeing any issues with the module in my tests that should stop the release, so I'd say things look good on my end.

**Comment by TheElementalOfDestruction** [comment]
Ah, wait I see one issue which is that sometimes an error from lark can break out of the module, which is likely intended to be a MalformedEncapsulatedRtf error? I had a document with additional data after the end bracket (the data was blatantly corrupt from what I could see, although Outlook still magically understood it), and it raised an `UnexpectedTokenError`. The following two sets of code can pretty easily raise the error:
```rtf
{\rtf1}}
```
```rtf
{\rtf1}1
```
I would either expect these files to both have the `MalformedEncapsulatedRtf` error or to simply drop any excess content.

**Comment by seamustuohy** [comment]
Good catch. I've wrapped the rtf_parser so it properly wraps lark's unexpected input errors into the malformed encapsulated RTF exceptions.

**Comment by Rafiot** [comment]
I just gave a quick check and It seems fine on my end (PyMISP).

**Comment by TheElementalOfDestruction** [comment]
Looks like I can sometimes get a recursion error with some of my files due to the use of repr on the lark Tree classes, since they do that recursively. I'm guessing that the recursion error is coming from some of the trees ending up really deeply nested. text_extraction.py line 686 is where I usually get the recursion error, though it's rare. Unfortunately it also can take up a lot of time on some of my tests files, and since it's a log it might be better to have some way to forcibly disable those lines from running, or simply having them optionally enabled if they are needed.

**Pull request merged**
